# Site settings
title: deGif
email: kods@piksel.is
author: Rihards Gravis
description: "Gifs reverse engineered to code."
url: "http://degif.github.io"

# Gems
gems: [jekyll-paginate]

# Build settings
markdown: kramdown
permalink: pretty
paginate: 1
